services:
  db:
    image: postgres:16-alpine
    env_file: ./ops/dev.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./ops/dev.env
    environment:
      # DATABASE_URL: postgresql+psycopg://todouser:${POSTGRES_PASSWORD}@db:5432/todo
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - "8080:80"

secrets:
  db_password:
    file: ./ops/postgres_password

volumes:
  pgdata:
